### ISSUE TITLE
Review PDF for checkbox uniformity

### ISSUE THREAD

**Issue by alexfaig** [SuffolkLITLab/docassemble-PetProtection#27]
The checkboxes on the PDF aren't equal in size and look messy. We also need additional docket number lines

Link to PDF: https://apps-dev.suffolklitlab.org/playgroundtemplate/default/51/Protection_and_Care_of_Animals_ready_for_qc.pdf

**Comment by derekdinardo** [comment]
Additional docket number lines aren't needed.  A motion for a protective order covering animals will be related to a single docket number.

**Comment by derekdinardo** [comment]
[Protection_and_Care_of_Animals_2020_09_30.pdf](https://github.com/SuffolkLITLab/docassemble-PetProtection/files/5303147/Protection_and_Care_of_Animals_2020_09_30.pdf)

**Comment by derekdinardo** [comment]
Fixed check boxes
