### ISSUE TITLE
Add Click-out Screen for when Restraining Order has not been issued

### ISSUE THREAD

**Issue by alexfaig** [SuffolkLITLab/docassemble-PetProtection#4]
Page id: restraining order requested

For the yes/no "has a restraining order been issued?" question, Maeve and Caroline mentioned we need a click-out screen that ends the interview if the user chooses "no." The interview should not proceed if the user chooses "no." (page ID: name of form).

**Comment by derekdinardo** [comment]
Kick out screen needs language.

**Comment by derekdinardo** [comment]
Kick out screen now has language, option to direct user to 209A interview, and phone number to safelink
