### ISSUE TITLE
Remove first court question

### ISSUE THREAD

**Issue by alexfaig** [SuffolkLITLab/docassemble-PetProtection#7]
Page id: name of court

Maeve, Michelle, and Caroline mentioned that we should get rid of the "name of court" question because the next question (page id: court information) is a basic question that already covers this. You may need to write code into the playground that allows the "court information" to populate all the necessary court information fields in the PDF. Refer to the recording of the review session from 00:13:00 to 00:16:00.

**Comment by derekdinardo** [comment]
How can the court division be extrapolated from the court information page?

**Comment by derekdinardo** [comment]
closed
